# Generated by Django 6.0.4 on 2026-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_models_name_auditlog_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='doctors/profiles/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='doctors/signatures/'),
        ),
    ]
